import React from 'react'
import Head from 'next/head'
import { Box } from '@chakra-ui/layout'


const Header = ({title}) => {
    return (
        <Box>
            <Head>
                <title> {title} • Sidebrief</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </Box>
    )
}

export default Header
